# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 59703ee4f735cb48fb534160abfb23feffda16ad8ead82e4a74ce2e9ad518c8297589358d49af80413c004dc6ccb113db74c760f617e8745bb2262035cbebee0

test:
  secret_key_base: 8d93ff6af1b1025ad324d8844f3dbba7bda56946ae1a1be32e3e0107eaaf84ad3da1fd6d70c4d2b92e1be6c11f8e7a1f63fb10da15803a450be203b30b0d342e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
